esphome:
  name: ac-ir

esp8266:
  board: esp8285
  
# Enable logging
logger:
  #  but not over serial/usb
  #  baud_rate: 0

# Enable Home Assistant API
api:
  password: !secret api_pw

ota:
  password: !secret ota_pw

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw
  domain: .intern.hild1.no
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "AC-IR Internal Fallback Hotspot"
    password: !secret wifi_backup_pw

captive_portal:

web_server:
  port: 80
  
remote_receiver:
  pin:
    number: GPIO14
    inverted: true
  dump: all
  
# Example configuration entry
remote_transmitter:
  pin: 
    number: GPIO04
  carrier_duty_percent: 50%

climate:
  - platform: toshiba
    name: "Living Room AC"
    model: "GENERIC"
