esphome:
  name: ac-ir

esp8266:
  board: esp8285
  
# Enable logging
logger:
  #  but not over serial/usb
  #  baud_rate: 0

# Enable Home Assistant API
api:
  password: !secret api_pw

ota:
  password: !secret ota_pw

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw
  domain: .intern.hild1.no
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "AC-IR Internal Fallback Hotspot"
    password: !secret wifi_backup_pw

captive_portal:

web_server:
  port: 80
  
# remote_receiver:
#   id: rr
#   pin:
#     number: GPIO14
#     inverted: true
#   dump: all
  
remote_transmitter:
  id: rt
  pin: 
    number: GPIO04
    # inverted: false # works in both?
  carrier_duty_percent: 50%

climate:
  - platform: coolix
    # no presets avaliable
    # swing mode off/vertical (sends vertical followed by off, does not remeber state?)
    name: "Bedroom AC Coolix"
    transmitter_id: rt
    supports_heat: false

  - platform: midea_ir
    # preset: sleep, boost. sleep works, boost does nothing. 
    # swing mode off/vertical (sends vertical followed by off, does not remeber state?)
    # swing mode not visible in mobile app?
    name: "Bedroom AC Midea"
    transmitter_id: rt
    supports_heat: false
