substitutions:
  devicename: "v0_power"

esphome:
  name: "v0-power"

esp8266:
  board: esp8285
  restore_from_flash: true

preferences:
  flash_write_interval: 5min

logger:
  # Disable usb/uart logging
  baud_rate: 0

api:
  password: !secret api_pw

ota:
  password: !secret ota_pw

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw
  domain: .intern.hild1.no

  ap:
    ssid: "${devicename}-AP"
    password: !secret wifi_backup_pw

web_server:
  port: 80

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    id: "${devicename}_button"
    on_press:
      - switch.toggle: button_switch

output:
  - platform: gpio
    id: led_red_io
    pin: 
      number: GPIO00
      inverted: true

light:
  - platform: status_led
    id: led_blue
    internal: true
    restore_mode: ALWAYS_OFF
    pin: 
      number: GPIO02
      inverted: true
  - platform: binary
    id: led_red
    output: led_red_io
    internal: true
    restore_mode: ALWAYS_OFF

switch:
  - platform: template
    name: "${devicename}_relay"
    icon: mdi:power
    optimistic: true
    restore_mode: ALWAYS_OFF
    lambda: 'return id(relay).state;'
    id: button_switch
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: led_red
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: led_red

  - platform: gpio
    pin: GPIO15
    id: relay
    restore_mode: ALWAYS_OFF
