esphome:
  name: v0-internal

esp8266:
  board: esp01_1m

# Enable logging
logger:
  #  baud_rate: 0

# Enable Home Assistant API
api:
  password: !secret api_pw

ota:
  password: !secret ota_pw

wifi:
  ssid: !secret wifi_ssid_test
  password: !secret wifi_pw
  domain: .test.hild1.no
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "V0-Internal Fallback Hotspot"
    password: !secret wifi_backup_pw

captive_portal:

web_server:
  port: 80

http_request:
  useragent: "esphome/v0-internal"
  timeout: 2s
  esp8266_disable_ssl_support: true

binary_sensor:
  - platform: gpio
    name: "RPI Ready to lose power"
    pin:
      number: GPIO3
      mode:
        input: true
    filters:
       - delayed_off: 1000ms
       - autorepeat:
         # After 3 seconds i should already be turned off
         - delay: 3s
           time_off: 100ms
           time_on: 100ms
    on_press:
      - http_request.post:
          url: http://v0-power.intern.hild1.no/switch/v0_power_relay/turn_off
